### ISSUE TITLE
catkin build fail

### ISSUE THREAD

**Issue by sz73** [ethz-asl/polygon_coverage_planning#15]
Hi everyone,

unfortunately I ran into problems when trying to execute catkin build. It appears to be related to missing eigen-XX.cmake files. Could be the error coming up while executing "wstool update" contribute to this problem? I have followed the description in the readme.md but still encounter this problem. Could you please help me? Thank you very much!

Here is what I get when executing wstool update 

```ruby
(base) simon@simon-ThinkPad-T480:~/catkin_ws/src$ wstool update
[catkin_simple] Updating /home/simon/catkin_ws/src/catkin_simple
[catkin_simple] Done.
[cgal_catkin] Updating /home/simon/catkin_ws/src/cgal_catkin
WARNING [vcstools] Command failed: 'git checkout feature/4.14'
 run at: '/home/simon/catkin_ws/src/cgal_catkin'
 errcode: 1:
error: pathspec 'feature/4.14' did not match any file(s) known to git.
[/vcstools]
[mav_comm] Updating /home/simon/catkin_ws/src/mav_comm
[mav_comm] Done.
[mav_trajectory_generation] Updating /home/simon/catkin_ws/src/mav_trajectory_generation
[mav_trajectory_generation] Done.
Exception caught during install: Error processing 'cgal_catkin' : [cgal_catkin] Update Failed of /home/simon/catkin_ws/src/cgal_catkin

ERROR in config: Error processing 'cgal_catkin' : [cgal_catkin] Update Failed of /home/simon/catkin_ws/src/cgal_catkin

```
And for catkin build:

```ruby

(base) simon@simon-ThinkPad-T480:~/catkin_ws/src$ catkin build
----------------------------------------------------------
Profile:                     default
Extending:        [explicit] /opt/ros/melodic
Workspace:                   /home/simon/catkin_ws
----------------------------------------------------------
Build Space:        [exists] /home/simon/catkin_ws/build
Devel Space:        [exists] /home/simon/catkin_ws/devel
Install Space:      [unused] /home/simon/catkin_ws/install
Log Space:          [exists] /home/simon/catkin_ws/logs
Source Space:       [exists] /home/simon/catkin_ws/src
DESTDIR:            [unused] None
----------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
----------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
----------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
----------------------------------------------------------
Workspace configuration appears valid.
----------------------------------------------------------
[build] Found '18' packages in 0.0 seconds.                                                                                                                                                                       
[build] Package table is up to date.                                                                                                                                                                              
Starting  >>> catkin_simple                                                                                                                                                                                       
Starting  >>> mav_msgs                                                                                                                                                                                            
Finished  <<< catkin_simple                                     [ 0.1 seconds ]                                                                                                                                   
Starting  >>> cuckoo_time_translator_algorithms                                                                                                                                                                   
Starting  >>> mav_2d_coverage_planning_benchmark                                                                                                                                                                  
Starting  >>> mav_visualization                                                                                                                                                                                   
Starting  >>> polygon_coverage_solvers                                                                                                                                                                            
Finished  <<< polygon_coverage_solvers                          [ 0.2 seconds ]                                                                                                                                   
Starting  >>> polygon_coverage_geometry                                                                                                                                                                           
Finished  <<< cuckoo_time_translator_algorithms                 [ 0.3 seconds ]                                                                                                                                   
Starting  >>> cuckoo_time_translator                                                                                                                                                                              
Starting  >>> cuckoo_time_translator_python                                                                                                                                                                       
Finished  <<< mav_msgs                                          [ 0.5 seconds ]                                                                                                                                   
Starting  >>> mav_planning_msgs                                                                                                                                                                                   
Starting  >>> mav_trajectory_generation                                                                                                                                                                           
Finished  <<< mav_2d_coverage_planning_benchmark                [ 0.2 seconds ]                                                                                                                                   
__________________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << cuckoo_time_translator:make /home/simon/catkin_ws/logs/cuckoo_time_translator/build.make.001.log                                                                                                    
Traceback (most recent call last):
  File "/home/simon/catkin_ws/src/cgal_catkin/cuckoo_time_translator/cfg/DeviceTimeTranslator.cfg", line 4, in <module>
    from dynamic_reconfigure.parameter_generator_catkin import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/__init__.py", line 38, in <module>
    import roslib
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
make[2]: *** [/home/simon/catkin_ws/devel/.private/cuckoo_time_translator/include/cuckoo_time_translator/DeviceTimeTranslatorConfig.h] Error 1
make[2]: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "/home/simon/catkin_ws/src/cgal_catkin/cuckoo_time_translator/cfg/MockCuckooClock.cfg", line 4, in <module>
    from dynamic_reconfigure.parameter_generator_catkin import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/__init__.py", line 38, in <module>
    import roslib
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
make[2]: *** [/home/simon/catkin_ws/devel/.private/cuckoo_time_translator/include/cuckoo_time_translator/MockCuckooClockConfig.h] Error 1
make[1]: *** [CMakeFiles/cuckoo_time_translator_gencfg.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
cd /home/simon/catkin_ws/build/cuckoo_time_translator; catkin build --get-env cuckoo_time_translator | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
..................................................................................................................................................................................................................
Failed     << cuckoo_time_translator:make                       [ Exited with code 2 ]                                                                                                                            
Failed    <<< cuckoo_time_translator                            [ 0.3 seconds ]                                                                                                                                   
Abandoned <<< mav_trajectory_generation_ros                     [ Unrelated job failed ]                                                                                                                          
Abandoned <<< mav_trajectory_generation_example                 [ Unrelated job failed ]                                                                                                                          
Abandoned <<< polygon_coverage_msgs                             [ Unrelated job failed ]                                                                                                                          
Abandoned <<< polygon_coverage_planners                         [ Unrelated job failed ]                                                                                                                          
Abandoned <<< polygon_coverage_ros                              [ Unrelated job failed ]                                                                                                                          
Abandoned <<< rviz_polygon_tool                                 [ Unrelated job failed ]                                                                                                                          
Finished  <<< cuckoo_time_translator_python                     [ 0.3 seconds ]                                                                                                                                   
__________________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << mav_visualization:cmake /home/simon/catkin_ws/logs/mav_visualization/build.cmake.002.log                                                                                                            
CMake Error at /home/simon/catkin_ws/devel/share/catkin_simple/cmake/catkin_simple-extras.cmake:38 (find_package):
  By not providing "Findeigen_catkin.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "eigen_catkin", but CMake did not find one.

  Could not find a package configuration file provided by "eigen_catkin" with
  any of the following names:

    eigen_catkinConfig.cmake
    eigen_catkin-config.cmake

  Add the installation prefix of "eigen_catkin" to CMAKE_PREFIX_PATH or set
  "eigen_catkin_DIR" to a directory containing one of the above files.  If
  "eigen_catkin" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:5 (catkin_simple)


cd /home/simon/catkin_ws/build/mav_visualization; catkin build --get-env mav_visualization | catkin env -si  /usr/bin/cmake /home/simon/catkin_ws/src/mav_trajectory_generation/mav_visualization --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/simon/catkin_ws/devel/.private/mav_visualization -DCMAKE_INSTALL_PREFIX=/home/simon/catkin_ws/install; cd -
..................................................................................................................................................................................................................
Failed     << mav_visualization:cmake                           [ Exited with code 1 ]                                                                                                                            
Failed    <<< mav_visualization                                 [ 0.8 seconds ]                                                                                                                                   
__________________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << polygon_coverage_geometry:cmake /home/simon/catkin_ws/logs/polygon_coverage_geometry/build.cmake.001.log                                                                                            
CMake Error at /home/simon/catkin_ws/devel/share/catkin_simple/cmake/catkin_simple-extras.cmake:38 (find_package):
  By not providing "Findcgal_catkin.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "cgal_catkin", but CMake did not find one.

  Could not find a package configuration file provided by "cgal_catkin" with
  any of the following names:

    cgal_catkinConfig.cmake
    cgal_catkin-config.cmake

  Add the installation prefix of "cgal_catkin" to CMAKE_PREFIX_PATH or set
  "cgal_catkin_DIR" to a directory containing one of the above files.  If
  "cgal_catkin" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:5 (catkin_simple)


cd /home/simon/catkin_ws/build/polygon_coverage_geometry; catkin build --get-env polygon_coverage_geometry | catkin env -si  /usr/bin/cmake /home/simon/catkin_ws/src/polygon_coverage_planning/polygon_coverage_geometry --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/simon/catkin_ws/devel/.private/polygon_coverage_geometry -DCMAKE_INSTALL_PREFIX=/home/simon/catkin_ws/install; cd -
..................................................................................................................................................................................................................
Failed     << polygon_coverage_geometry:cmake                   [ Exited with code 1 ]                                                                                                                            
Failed    <<< polygon_coverage_geometry                         [ 0.8 seconds ]                                                                                                                                   
Finished  <<< mav_planning_msgs                                 [ 0.6 seconds ]                                                                                                                                   
__________________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << mav_trajectory_generation:cmake /home/simon/catkin_ws/logs/mav_trajectory_generation/build.cmake.002.log                                                                                            
CMake Error at /home/simon/catkin_ws/devel/share/catkin_simple/cmake/catkin_simple-extras.cmake:38 (find_package):
  By not providing "Findeigen_catkin.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "eigen_catkin", but CMake did not find one.

  Could not find a package configuration file provided by "eigen_catkin" with
  any of the following names:

    eigen_catkinConfig.cmake
    eigen_catkin-config.cmake

  Add the installation prefix of "eigen_catkin" to CMAKE_PREFIX_PATH or set
  "eigen_catkin_DIR" to a directory containing one of the above files.  If
  "eigen_catkin" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:5 (catkin_simple)


cd /home/simon/catkin_ws/build/mav_trajectory_generation; catkin build --get-env mav_trajectory_generation | catkin env -si  /usr/bin/cmake /home/simon/catkin_ws/src/mav_trajectory_generation/mav_trajectory_generation --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/simon/catkin_ws/devel/.private/mav_trajectory_generation -DCMAKE_INSTALL_PREFIX=/home/simon/catkin_ws/install; cd -
..................................................................................................................................................................................................................
Failed     << mav_trajectory_generation:cmake                   [ Exited with code 1 ]                                                                                                                            
Failed    <<< mav_trajectory_generation                         [ 0.8 seconds ]                                                                                                                                   
[build] Summary: 7 of 17 packages succeeded.                                                                                                                                                                      
[build]   Ignored:   1 packages were skipped or are blacklisted.                                                                                                                                                  
[build]   Warnings:  None.                                                                                                                                                                                        
[build]   Abandoned: 6 packages were abandoned.                                                                                                                                                                   
[build]   Failed:    4 packages failed.                                                                                                                                                                           
[build] Runtime: 1.7 seconds total.                                                                                                                                                                               
(base) simon@simon-ThinkPad-T480:~/catkin_ws/src$ wstool update
[catkin_simple] Updating /home/simon/catkin_ws/src/catkin_simple
[catkin_simple] Done.
[cgal_catkin] Updating /home/simon/catkin_ws/src/cgal_catkin
WARNING [vcstools] Command failed: 'git checkout feature/4.14'
 run at: '/home/simon/catkin_ws/src/cgal_catkin'
 errcode: 1:
error: pathspec 'feature/4.14' did not match any file(s) known to git.
[/vcstools]
[mav_comm] Updating /home/simon/catkin_ws/src/mav_comm
[mav_comm] Done.
[mav_trajectory_generation] Updating /home/simon/catkin_ws/src/mav_trajectory_generation
[mav_trajectory_generation] Done.
Exception caught during install: Error processing 'cgal_catkin' : [cgal_catkin] Update Failed of /home/simon/catkin_ws/src/cgal_catkin

ERROR in config: Error processing 'cgal_catkin' : [cgal_catkin] Update Failed of /home/simon/catkin_ws/src/cgal_catkin

(base) simon@simon-ThinkPad-T480:~/catkin_ws/src$ 
```

**Comment by rikba** [comment]
Hi @sz73 

I tried simplifying the installation. Can you clean your catkin_ws (remove it) and restart the retry the installation?

**Comment by sz73** [comment]
Hey @rikba 

the new merge solved this very problem! Thank you very much! :D
Unfortunately, I ran into another problem now.
